version: "3.8"

services:
  media-cleanerr:
    build: .
    container_name: media-cleanerr
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config
    environment:
      # Application Settings
      - FLASK_APP=app.py
      - FLASK_DEBUG=1

    restart: unless-stopped
